source ex0_prepared_requests.sql
source ex1_model_tous_administratifs.sql
source ex2_model_tous_eleves.sql
source ex3_model_tous_enseignants.sql
source ex4_model_eleves_classe.sql
source ex5_model_parents_classe.sql
source ex6_model_profs_classe.sql
source ex7_model_profs_principaux_niveau.sql
source ex8_model_tous_parents.sql

